defaults:
  # Defaults are applied in the order they appear, so later defaults override earlier ones.

  - base_config  # Defaults defined in `Config` from `config.py`
  - _self_  # Defaults defined below

  # - override hydra/launcher: submitit_local
  - override hydra/launcher: submitit_slurm


hydra:
  sweeper:
    params:
      # We will sweep over these parameters when the `--multirun` flag is used.

      seed: 0, 1, 2, 3, 4
      # model: gpt2-untrained, gpt2, java-gpt2

      # learning_rate: 0.00001, 0.0001, 0.001
      # warmup_proportion: 0.0002, 0.002, 0.02
      # weight_decay: 0.001, 0.01, 0.1


  # SLURM-specific arguments
  launcher:
    tasks_per_node: 1
    cpus_per_task: 8
    gpus_per_node: 1
    timeout_min: 4320 # 3 days
    mem_gb: 30

  job:
    # Prevent hydra from automatically changing the working directory of each experiment.
    chdir: False