defaults:
  # Defaults are applied in the order they appear, so later defaults override earlier ones.

  - base_config  # Defaults defined in `Config` from `config.py`
  - _self_  # Defaults defined below

  # - override hydra/launcher: submitit_local
  - override hydra/launcher: submitit_slurm


hydra:
  sweeper:
    params:
      # We will sweep over these parameters when the `--multirun` flag is used.

      seed: 0, 1, 2

      # model: gpt2, codeparrot, java-gpt2, incoder-1B, incoder-6B 
      model: java-gpt2

      data_source: null, boxoban-chars, boxoban-text, l_maze
      # data_source: boxoboan-chars

      # chunk_size: 128, 256, 512

  # SLURM-specific arguments
  launcher:
    tasks_per_node: 1
    cpus_per_task: 10
    gpus_per_node: 1
    timeout_min: 1440
    mem_gb: 30

  job:
    # Prevent hydra from automatically changing the working directory of each experiment.
    chdir: False